export { EditorialColumns } from './editorial/components/EditorialColumns'
export { EditorialSurface } from './editorial/components/EditorialSurface'
export { FlowLines } from './editorial/components/FlowLines'
export { useTextFlow } from './editorial/hooks/useTextFlow'
export { flowText } from './editorial/lib/flowText'
export { carveLineSlots, createLineSlotResolver, getCircleBlockedLineRangeForRow, pickWidestLineSlot } from './editorial/lib/lineSlots'

export type { EditorialPlacement, EditorialFigure } from './editorial/lib/editorialFigures'
export type { EditorialTrack } from './editorial/lib/editorialTracks'
export type { EditorialColumnsProps } from './editorial/components/EditorialColumns'
export type { EditorialSurfaceProps } from './editorial/components/EditorialSurface'
export type { FlowLineRenderInput, FlowLinesProps, FlowRenderableLine } from './editorial/components/FlowLines'
export type { UseTextFlowInput, UseTextFlowResult } from './editorial/hooks/useTextFlow'
export type { PositionedLine, TextFlowInput, TextFlowResult } from './editorial/lib/flowText'
export type { LineSlot } from './editorial/lib/lineSlots'
