export { PEditorialFigure } from './lib/editorialFigures'
export { PEditorialTrack } from './lib/editorialTracks'
export { PEditorialColumns } from './components/PEditorialColumns'
export { PEditorialSurface } from './components/PEditorialSurface'
export { useTextFlow } from './hooks/useTextFlow'
export { flowText } from './lib/flowText'
export { carveLineSlots, createLineSlotResolver, getCircleBlockedLineRangeForRow, pickWidestLineSlot } from './lib/lineSlots'

export type { EditorialPlacement, PEditorialFigureProps } from './lib/editorialFigures'
export type { PEditorialTrackProps } from './lib/editorialTracks'
export type { PEditorialColumnsProps } from './components/PEditorialColumns'
export type { PEditorialSurfaceProps } from './components/PEditorialSurface'
export type { UseTextFlowInput, UseTextFlowResult } from './hooks/useTextFlow'
export type { PositionedLine, TextFlowInput, TextFlowResult } from './lib/flowText'
export type { LineSlot } from './lib/lineSlots'
