export * from '@chenglou/pretext'

export { useElementWidth } from './hooks/useElementWidth'
export { usePreparedText } from './hooks/usePreparedText'
export { usePreparedSegments } from './hooks/usePreparedSegments'
export { usePretextLayout } from './hooks/usePretextLayout'
export { usePretextLines } from './hooks/usePretextLines'
export { PText } from './components/PText'
export { PEditorialFigure } from './lib/editorialFigures'
export { PEditorialTrack } from './lib/editorialTracks'
export { PEditorialColumns } from './components/PEditorialColumns'
export { PEditorialSurface } from './components/PEditorialSurface'
export { useTextFlow } from './hooks/useTextFlow'
export { flowText } from './lib/flowText'
export { carveLineSlots, createLineSlotResolver, getCircleBlockedLineRangeForRow, pickWidestLineSlot } from './lib/lineSlots'

export type { ElementWidthResult } from './hooks/useElementWidth'
export type { PrepareOptions, UsePreparedTextInput, UsePreparedTextResult } from './hooks/usePreparedText'
export type { UsePreparedSegmentsInput, UsePreparedSegmentsResult } from './hooks/usePreparedSegments'
export type { UsePretextLayoutInput, UsePretextLayoutResult } from './hooks/usePretextLayout'
export type { UsePretextLinesInput, UsePretextLinesResult } from './hooks/usePretextLines'
export type { PTextProps, PTextMeasure, PTextTag } from './components/PText'
export type { EditorialPlacement, PEditorialFigureProps } from './lib/editorialFigures'
export type { PEditorialTrackProps } from './lib/editorialTracks'
export type { PEditorialColumnsProps } from './components/PEditorialColumns'
export type { PEditorialSurfaceProps } from './components/PEditorialSurface'
export type { UseTextFlowInput, UseTextFlowResult } from './hooks/useTextFlow'
export type { PositionedLine, TextFlowInput, TextFlowResult } from './lib/flowText'
export type { LineSlot } from './lib/lineSlots'
